# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e1f8b2540df91d9630404a34fca3115cef8be6247bde3000346d1f653079530278fa45a94c78fec1f084c43fb86d1bbb7fb920802a2991a2f318297a11dbce

test:
  secret_key_base: 4ca00c4311c47ab70f0172a9fc2e41c90acbc5b647f6460f8caeba438a336a86fe7ba400539b9a961258adb5424d17f6d9fe45cb8b7d6d2604015268d7919371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
